---
- name: Check epel
  shell: yum-config-manager epel | grep -q 'enabled = True'
  changed_when: False
  ignore_error: True
  register: epel_status

- name: Install epel-release
  yum:
    name: epel-release
    state: present

- name: Enabled epel
  command: yum-config-manager --enable epel
  when: epel_status.rc != 0
